#!/bin/bash

APP="ipr_api"

START_DEPLOY=true
CLEAN_DEPLOY=true

# prevent re-installing node modules; this defaults to "."
GIT_CLEAN_PATHS="_build rel priv/static"

STAGING_HOSTS="18.139.224.38" # staging / test hosts separated by space
STAGING_USER="deploy" # local user at staging hosts
TEST_AT="/home/deploy/apps"

PRODUCTION_HOSTS="13.251.147.9"
# PRODUCTION_HOSTS="18.139.224.38"
PRODUCTION_USER="deploy"
DELIVER_TO="/home/deploy/apps"

if [[ "$DEPLOY_ENVIRONMENT" = "staging" ]]; then
  BUILD_HOST="$STAGING_HOSTS"
elif [[ "$DEPLOY_ENVIRONMENT" = "production" ]]; then
  BUILD_HOST="$PRODUCTION_HOSTS"
fi

BUILD_USER="deploy"
BUILD_AT="/tmp/edeliver/$APP/builds"

# For Phoenix projects, symlink prod.secret.exs to our tmp source
pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/deploy/apps/$APP/secret/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    status "Linking '$_prod_secret_path'"
    __sync_remote "
      [ -f ~/.profile ] && source ~/.profile
      mkdir -p '$BUILD_AT'
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
      cd '$BUILD_AT/config'
    "
  fi
}